name: flip_package
description: Template for Flutter Package project.
version: 0.0.1
author: Steven Smith
homepage: http://www.icodeforyou.com

environment:
  sdk: ">=2.13.4 <3.0.0" #Dart SDK 1-JUL-2021
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
