name: flip_package
description: Template for Flutter Package project.
version: 0.0.1
author: Steven Smith
homepage: http://www.icodeforyou.com

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
